INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('Admin','Admin','A');
INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('User','User','A');
INSERT ROLE(NAME_ROLE,DESC_ROLE,STATUS)
VALUES('Guest','Guest','A');