INSERT USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,BIRTH,STATUS)
VALUES('fkrumm','123','Fredrick','Krumm','1996-2-02','A');
INSERT USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,BIRTH,STATUS)
VALUES('jdunning','123','Jaymie','Dunning','1993-10-05','A');
INSERT USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,BIRTH,STATUS)
VALUES('krayford','123','Kristy','Rayford','1990-10-06','A');
INSERT USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,BIRTH,STATUS)
VALUES('fredington','123','Faye','Redington','1995-5-03','A');
INSERT USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,BIRTH,STATUS)
VALUES('bstinebaugh','123','Bobbye','Stinebaugh','2000-9-14','A');
